{{- if and .Values.googleCalendar.enabled (not .Values.googleCalendar.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bmw-saver.fullname" . }}-gcal
  labels:
    {{- include "bmw-saver.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.googleCalendar.credentialsKey }}: {{ required "Google Calendar credentials are required" .Values.googleCalendar.credentials }}
{{- end }} 